<?php

declare(strict_types=1);

/**
 * This file is part of Meridian Ecommerce Platform.
 *
 * @package    Database\Migrations
 * @author     L K Lalitesh <lalitesh@live.com>
 * @company    Bytics Lab
 * @copyright  2026 Bytics Lab. All rights reserved.
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('url_rewrites', function (Blueprint $table) {
            $table->char('id', 26)->primary();
            $table->char('channel_id', 26)->nullable()->index();

            $table->string('request_path', 500)->index();
            $table->string('target_path', 500);

            // redirect_type: 0 = no redirect (internal), 301, 302
            $table->unsignedSmallInteger('redirect_type')->default(0);

            // entity_type: 'product', 'category', 'cms_page', 'custom'
            $table->string('entity_type', 30)->nullable();
            $table->char('entity_id', 26)->nullable();

            $table->boolean('is_autogenerated')->default(false);

            $table->timestamps();

            $table->unique(['channel_id', 'request_path']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('url_rewrites');
    }
};
